---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-db-secret
  namespace: seerr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore

  data:
    - secretKey: DB_USER
      remoteRef:
        key: database/seerr
        property: db_user

    - secretKey: DB_PASS
      remoteRef:
        key: database/seerr
        property: db_password

