apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-pvc
  namespace: seerr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: seerr-config-pv
