---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-password-source
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: sonarr-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: sonarr
        property: db_user

    - secretKey: password
      remoteRef:
        key: sonarr
        property: db_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-db-secret
  namespace: sonarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore

  data:
    - secretKey: username
      remoteRef:
        key: sonarr
        property: db_user

    - secretKey: password
      remoteRef:
        key: sonarr
        property: db_password
