---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: sonarr
          image: docker.wevelsiep.com/linuxserver/sonarr:4.0.15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            seccompProfile:
              type: "RuntimeDefault"
          readinessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3                
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-media
              mountPath: /media
            - name: sonarr-seedbox
              mountPath: /downloads                          
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-pvc
        - name: sonarr-media
          persistentVolumeClaim:
            claimName: sonarr-media-pvc
        - name: sonarr-seedbox
          persistentVolumeClaim:
            claimName: sonarr-seedbox-pvc
