apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-config-secret
  namespace: sonarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: sonarr-config-secret
  data:
    - secretKey: SONARR__POSTGRES__USER
      remoteRef:
        key: database/sonarr
        property: db_user
    - secretKey: SONARR__POSTGRES__PASSWORD
      remoteRef:
        key: database/sonarr
        property: db_password
    - secretKey: SONARR__AUTH__APIKEY
      remoteRef:
        key: apps/sonarr
        property: apikey