apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
#      version: 1.15.5 
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
