apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: true
    k8sServiceHost: 192.168.20.20
    k8sServicePort: 6443
    operator:
      replicas: 1
    ipam:
      mode: "kubernetes"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    externalIPs:
      enabled: true
    k8sClientRateLimit:
      qps: 50
      burst: 200
    rollOutCiliumPods: true
