apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
