kubeProxyReplacement: true
k8sServiceHost: 192.168.20.20
k8sServicePort: 6443
operator:
  replicas: 1
ipam:
  mode: "kubernetes"
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    
l2announcements:
  enabled: true

externalIPs:
  enabled: true

k8sClientRateLimit:
  qps: 50
  burst: 200

rollOutCiliumPods: true
