apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whoami-oidc
  namespace: whoami
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore
  target:
    name: whoami-oidc
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_SECRET
      remoteRef:
        key: testing/whoami
        property: ENCRYPTION_SECRET
    - secretKey: CLIENT_ID
      remoteRef:
        key: testing/whoami
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: testing/whoami
        property: CLIENT_SECRET
