apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-repo
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-repo
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: ""
