apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m
  releaseName: cnpg
  targetNamespace: cnpg-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg-repo
        namespace: flux-system