apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    monitoring:
      enablePodMonitor: true
