apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: suggestarr-db
  namespace: suggestarr-db
spec:
  name: suggestarr-db
  owner: suggestarr-user
  cluster:
    name: suggestarr-postgres-cluster
