apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: homepage
          image: docker.wevelsiep.com/gethomepage/homepage:v1.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: homepage
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: homepage
              mountPath: /app/config
              subPath: config

            - name: homepage
              mountPath: /app/public/icons
              subPath: icons

            - name: homepage
              mountPath: /app/public/images
              subPath: images

      volumes:
        - name: homepage
          persistentVolumeClaim:
            claimName: homepage-pvc
