apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: needle-config-pvc
  namespace: needle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: needle-data-pvc
  namespace: needle
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: needle-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: needle-db-pvc
  namespace: needle
  labels:
    app.kubernetes.io/name: needle-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-retain
