apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr-secret
  namespace: unpackerr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore
  target:
    name: unpackerr-secret
  data:
    - secretKey: UN_RADARR_0_API_KEY
      remoteRef:
        key: apps/radarr
        property: apikey
    - secretKey: UN_SONARR_0_API_KEY
      remoteRef:
        key: apps/sonarr
        property: apikey
    - secretKey: UN_LIDARR_0_API_KEY
      remoteRef:
        key: apps/lidarr
        property: apikey
    - secretKey: UN_WHISPARR_0_API_KEY
      remoteRef:
        key: apps/whisparr
        property: apikey
