apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-repo
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "v1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system