apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
  namespace: comfyui
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: comfyui-pv
