apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data-pvc
  namespace: pocketid
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pocketid-pv
