apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-db-ingress
  namespace: openwebui-db
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: openwebui
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - fromEndpoints:
        - {}
