apiVersion: v1
kind: Namespace
metadata:
  name: openwebui-db
  labels:
    network-dns-egress: "true"
    network-apiserver-egress: "true"
    network-s3-egress: "true"
    network-monitoring-ingress: "true"
    network-cnpg-ingress: "true"
