apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-db-traffic
  namespace: openwebui-db
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: openwebui
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - {}
