apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smb-csi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-driver-smb
      sourceRef:
        kind: HelmRepository
        name: smb-csi
      version: "v1.19.0"
  interval: 1h0m0s
  releaseName: csi-driver-smb
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      runOnControlPlane: true
