apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: smb-csi
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
