apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-config-secret
  namespace: radarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: radarr-config-secret
  data:
    - secretKey: RADARR__POSTGRES__USER
      remoteRef:
        key: database/radarr
        property: db_user
    - secretKey: RADARR__POSTGRES__PASSWORD
      remoteRef:
        key: database/radarr
        property: db_password
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: apps/radarr
        property: apikey