apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: radarr-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: radarr-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-seedbox-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: radarr-seedbox-pv

