apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suggestarr-config-pvc
  namespace: suggestarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: suggestarr-config-pv
