apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - database-credentials.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - storage.yaml
