apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-pvc
  namespace: pocketid
  labels:
    app.kubernetes.io/name: pocketid
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
