apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr-config-secret
  namespace: lidarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore
  target:
    name: lidarr-config-secret
  data:
    - secretKey: LIDARR__POSTGRES__USER
      remoteRef:
        key: database/lidarr
        property: db_user
    - secretKey: LIDARR__POSTGRES__PASSWORD
      remoteRef:
        key: database/lidarr
        property: db_password
    - secretKey: LIDARR__AUTH__APIKEY
      remoteRef:
        key: apps/lidarr
        property: apikey
