apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: lidarr-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-media-pvc
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: lidarr-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-seedbox-pvc
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: lidarr-seedbox-pv
