apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: houndarr-pvc
  namespace: houndarr
  labels:
    app.kubernetes.io/name: houndarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-retain
