apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: houndarr-pvc
  namespace: houndarr
  labels:
    app.kubernetes.io/name: houndarr
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/garage-s3: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-retain
