apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup.yaml
  - cluster.yaml
  - cnp-egress.yaml
  - cnp-ingress.yaml
  - database.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
