---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgBuH6JgvpGVttn4bDJFa3pB1rFuSOB/8FEld7A3MIDPZRu6YKtPba6Yt+VZGAEQ6sCfR63XH75QQXn0r/FsQ26R/9ECL4/ZwUYuu+vmH/v09clqo8ItFKc+DfcpbgafGkJzI0PDckJDIU16XBTf/rdSIRM+K1Hsa9UtwsMkt8Q/beeAhfbiurNmWw7FV+NSlMA/4swB/W2IDuzmdD5l8c4hWvBeprHnvwMT0MXt8oLE+06ijfIYc4NTlkRrYvdfpXuWhg9DjuI4V59FxwPJE0jMZsd5mX720uqfHnfkoe9X5CGbZ0HAxLUNIkfPfd+0WE2bzLmHBfw4JW+kaxBNxia/WSXylyVuJkRNPQmWIDgdqlHoqSTK3SDcWry4Z4P+b6sbfEqXKBQdN4A0aG56sEMFJfznstx/aDpPdfIm5/Lfdibfy0qOJIBVTFMJv5DsUnXNub91oovr3/JYsEocVmaAiq88ZiTxh23RPNf7/UETBfDmBWL94qzD13C4oxrGdUEkxtQKj5yc3TA2bpoH4Kv+nyFA8eHwN5NPpGQOTUUwkNTqtlugUSNm7CLeeclGWDQ+SLnY40DkEB0zhxZRsNQLrRj2zFXm7GXB5CKduVAm8xV586AAhR4GytJefry982A0dXfzOdZxwZz7R1vGgcG46r4xgw9wwDaxRQFrvD7aoUgZlHH1q+OQh5SG4Ll0HUtyI28YbJj0n8rBGgMPoOW1XkzlKyX7xgZWgaM1
  template:
    metadata:
      creationTimestamp: null
      name: vault-token
      namespace: external-secrets
    type: Opaque
