---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgClM8di6x8Pp/fcG/IML/9hBpRpetRrVqfO85030yfnOreNd2/9BYBZSYNQfys9xYB8KLAzuRs26C9/CYULCV2obEvQlmgrZotF5zTrj3Lwy90h//Mbldo1u4yVTl7IMK3OEwHL//i5wehspKz3kodE9FpTyLxWNxbub3tWHw+R+TQclVVXO3GDuMH08q7+FVvlILOm5hLIQu66m7Wo3c1leZr++a4bTh84ZbNLoRBD4+ThN4X4fcdN7gKxzHClhPVpa4FA9bFLWautJOE5iRDmy8nrKPJ2+MDx+/lV0Eb5p8NV8wmtfFvOZXAU7HijAmX2gk/eg2Z2Fl4+PWkkZETrauFKGkJTFy6hwpx/LG+HnxbUOGJO+4xumi5gwmeFoQmWvKqErD2t7uRXYkHhImXWgYxnWHny0teB22kTqHpBRZKRn1zG0L/y743FCwM5pW2TD6oeFgdgwd4Y92X2uJH30PnbXDgpy/oDatfS2wYJ+8wTJvUit7ZR69r+PIC52qV6tlsUlJCjUIso+9uB7tptEX6H1LxxD1YPa1Vjg7sqjZsiWpMuNr7Q1OOdrEdyeaEDxyqgTzL5bvItk2U9MpsFsdWjhwC9Po5JbiR88C1E0yn04iQkomxHeyaMwGFVKK9YlS0OS89VI/yW5EMPbTrOYyJalUBLBUp8MMRi7+3jK1nGg/5BSmPVZ2HyyuEJWPH9L0uZZgLz/GVW5LEQgTpepPTIaPtp2yWlAad3
  template:
    metadata:
      creationTimestamp: null
      name: vault-token
      namespace: external-secrets
    type: Opaque
