apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - uptimekuma.yaml
  - ntfy.yaml
#  - prometheus-stack.yaml
#  - grafana.yaml
#  - prometheus.yaml
#  - kube-state-metrics.yaml