apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: autobrr-db
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-kubernetes
  namespace: autobrr-db
spec:
  provider:
    vault:
      server: https://vault.wevelsiep.com
      path: kubernetes
      version: v2
      auth:
        jwt:
          path: jwt-kubernetes
          role: autobrr-db
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: vault-auth
            audiences:
              - vault
            expirationSeconds: 600
