---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3master01
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: k3master01
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:release
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2283
          env:
            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: DB_HOSTNAME
              value: immich-postgres-cluster-rw.immich-db.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE_NAME
              value: immich-db
          envFrom:
            - secretRef:
                name: immich-config-secret
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "4"
              memory: "8Gi"
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: "RuntimeDefault"
          readinessProbe:
            httpGet:
              path: /api/server/ping
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/server/ping
              port: 2283
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-data-pvc
        - name: tmp
          emptyDir: {}
