apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-config-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore
  target:
    name: immich-config-secret
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: database/immich
        property: db_user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: database/immich
        property: db_password
