apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downtify-download-pvc
  namespace: downtify
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: downtify-download-pv
