apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: seerr-postgres-cluster
  namespace: seerr-db
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    storageClass: "local-path"
    size: 10Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: s3-garage

  superuserSecret:
    name: postgres-superlogin

  managed:
    roles:
      - name: seerr-user
        ensure: present
        login: true
        passwordSecret:
          name: seerr-db-secret
