apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.20.30

    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
      websecure:
        port: 443
        expose: true
        exposedPort: 443

    ingressRoute:
      dashboard:
        enabled: true

    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-cert

    additionalArguments:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

    rbac:
      enabled: true
