deployment:
  kind: DaemonSet

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.20.30
    externalTrafficPolicy: Local
ports:
  web:
    port: 8080
    expose:
      default: true
    exposedPort: 8080
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 8443

ingressRoute:
  dashboard:
    enabled: true

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-cert

log:
  level: INFO

logs:
  access:
    enabled: true
    format: common

entryPoints:
  web:
    forwardedHeaders:
      insecure: true
  websecure:
    forwardedHeaders:
      insecure: true

providers:
  kubernetesCRD:
    allowCrossNamespace: false

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-wan