---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-password-source
  namespace: database
  labels:
    cnpg.io/reload: "true"    
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: radarr-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: prowlarr
        property: db_user

    - secretKey: password
      remoteRef:
        key: prowlarr
        property: db_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-db-secret
  namespace: prowlarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore

  data:
    - secretKey: username
      remoteRef:
        key: prowlarr
        property: db_user

    - secretKey: password
      remoteRef:
        key: prowlarr
        property: db_password
