apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-postgres-cluster
  namespace: linkwarden-db
spec:
  instances: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    storageClass: "local-path-delete"
    size: 10Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: s3-garage

  superuserSecret:
    name: postgres-superlogin

  managed:
    roles:
      - name: linkwarden-user
        ensure: present
        login: true
        passwordSecret:
          name: linkwarden-db-secret
