apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-postgres
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-cloudnative-pg
