apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sealed-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
