apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-pocketid
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/pocketid
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-traefik
