apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik-wan
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/traefik/wan
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-cert-manager-crs
