apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-smb-csi
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/smb-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-namespaces
