apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cilium
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
