apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - repository-hiddenkubernetes.yaml
  - infrastructure-namespaces.yaml
  - infrastructure-cilium.yaml
  - infrastructure-longhorn.yaml
  - infrastructure-nvidia.yaml
  - infrastructure-sealed-secrets.yaml
  - infrastructure-external-secrets.yaml
  - infrastructure-smb-csi.yaml
  - storage.yaml
  - infrastructure-cert-manager.yaml
  - infrastructure-traefik.yaml
  - apps-postgres.yaml
  - databases.yaml
  - platform.yaml
  - apps.yaml
  - apps-hidden.yaml
  - monitoring.yaml
  - testing.yaml
