apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-uptimekuma
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./monitoring/uptimekuma
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-traefik
