apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-kube-state-metrics
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./monitoring/kube-state-metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: monitoring-prometheus
