apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repository-hiddenkubernetes
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./repository/hiddenkubernetes
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
