apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-hidden
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./storage
  prune: false
  sourceRef:
    kind: GitRepository
    name: hidden-repo
  dependsOn:
    - name: repository-hiddenkubernetes
