apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autobrr-db
  - gallery-dl-db
  - lidarr-db
  - linkwarden-db
  - openwebui-db
  - pocketid-db
  - prowlarr-db
  - radarr-db
  - seerr-db
  - sonarr-db
  - wikijs-db