apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-client-ca
  namespace: traefik
spec:
  isCA: true
  commonName: homelab-mtls-client-ca
  secretName: mtls-client-ca
  duration: 87600h # 10y
  renewBefore: 720h # 30d
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
