apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - egress-allow-apiserver.yaml
  - egress-allow-dns.yaml
  - egress-allow-s3.yaml
  - egress-allow-world.yaml
  - egress-deny-all.yaml
  - ingress-allow-cnpg.yaml
  - ingress-allow-homepage.yaml
  - ingress-allow-monitoring.yaml
  - ingress-deny-all.yaml
