apiVersion: v1
kind: ConfigMap
metadata:
  name: qui-config
  namespace: qui
data:
  config.toml: |
    host = "0.0.0.0"
    port = 7476
    logLevel = "TRACE"
    checkForUpdates = true
    sessionSecret = "{{ .sessionSecret }}"
    databaseType = "postgres"
    postgresHost = "qui-postgres-cluster-rw.qui-db.svc.cluster.local"
    postgresPort = 5432
    postgresDatabase = "qui-db"
    postgresUser = "{{ .postgresUser }}"
    postgresPass = "{{ .postgresPass }}"
    postgresSSLMode = "disable"
