apiVersion: v1
kind: ConfigMap
metadata:
  name: qui-config
  namespace: qui
data:
  config.toml: |
    host = "0.0.0.0"
    port = 7476
    logLevel = "INFO"
    checkForUpdates = true
    sessionSecret = "{{ .sessionSecret }}"
    dataDir = "/data"
    databaseEngine = "postgres"
    databaseHost = "qui-postgres-cluster-rw.qui-db.svc.cluster.local"
    databasePort = 5432
    databaseName = "qui-db"
    databaseUser = "{{ .postgresUser }}"
    databasePassword = "{{ .postgresPass }}"
    databaseSSLMode = "disable"
