apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-config-secret
  namespace: qui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore
  target:
    name: qui-config-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: qui-config
            items:
              - key: config.toml
  data:
    - secretKey: postgresUser
      remoteRef:
        key: database/qui
        property: db_user
    - secretKey: postgresPass
      remoteRef:
        key: database/qui
        property: db_password
    - secretKey: sessionSecret
      remoteRef:
        key: apps/qui
        property: sessionSecret
