apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qui-seedbox-pvc
  namespace: qui
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: qui-seedbox-pv
