apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-env-secret
  namespace: gitea-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: gitea-runner-env-secret
    creationPolicy: Owner
  data:
    - secretKey: GITEA_INSTANCE_URL
      remoteRef:
        key: apps/gitea-runner
        property: GITEA_INSTANCE_URL

    - secretKey: GITEA_RUNNER_REGISTRATION_TOKEN
      remoteRef:
        key: apps/gitea-runner
        property: GITEA_RUNNER_REGISTRATION_TOKEN
