apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-runner-pvc
  namespace: gitea-runner
  labels:
    app.kubernetes.io/name: gitea-runner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-dind-cache-pvc
  namespace: gitea-runner
  labels:
    app.kubernetes.io/name: gitea-runner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
