apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr-config-secret
  namespace: autobrr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: autobrr-config-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: autobrr-config
            items:
              - key: config.toml
  data:
    - secretKey: postgresUser
      remoteRef:
        key: database/autobrr
        property: db_user
    - secretKey: postgresPass
      remoteRef:
        key: database/autobrr
        property: db_password
    - secretKey: sessionSecret
      remoteRef:
        key: apps/autobrr
        property: sessionSecret
