apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hidden-repo-auth
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: hidden-repo-auth
    creationPolicy: Owner
  data:
    - secretKey: identity
      remoteRef:
        key: hidden_repo
        property: private_key
    - secretKey: known_hosts
      remoteRef:
        key: hidden_repo
        property: known_hosts
