apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deemix-media-pvc
  namespace: deemix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: deemix-media-pv

