apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    storageClass: "local-path"
    size: 25Gi

  superuserSecret:
    name: postgres-superlogin

  managed:
    roles:
      - name: openwebui_user
        ensure: present
        login: true
        passwordSecret:
          name: openwebui-db-secret

      - name: linkwarden_user
        ensure: present
        login: true
        passwordSecret:
          name: linkwarden-db-secret

      - name: wikijs_user
        ensure: present
        login: true
        passwordSecret:
          name: wikijs-db-secret

      - name: sonarr_user
        ensure: present
        login: true
        passwordSecret:
          name: sonarr-db-secret

      - name: radarr_user
        ensure: present
        login: true
        passwordSecret:
          name: radarr-db-secret

      - name: lidarr_user
        ensure: present
        login: true
        passwordSecret:
          name: lidarr-db-secret


      - name: whisparr_user
        ensure: present
        login: true
        passwordSecret:
          name: whisparr-db-secret
