apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    storageClass: "local-path"
    size: 25Gi

  superuserSecret:
    name: postgres-superlogin

  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-kubernetes
      s3Credentials:
        accessKeyId:
          name: postgres-s3-secret
          key: s3_key_id
        secretAccessKey:
          name: postgres-s3-secret
          key: s3_secret_key
      endpointURL: https://s3.wevelsiep.com
      wal:
        compression: gzip

  managed:
    roles:
      - name: openwebui-user
        ensure: present
        login: true
        passwordSecret:
          name: openwebui-db-secret

      - name: linkwarden-user
        ensure: present
        login: true
        passwordSecret:
          name: linkwarden-db-secret

      - name: wikijs-user
        ensure: present
        login: true
        passwordSecret:
          name: wikijs-db-secret

      - name: sonarr-user
        ensure: present
        login: true
        passwordSecret:
          name: sonarr-db-secret

      - name: radarr-user
        ensure: present
        login: true
        passwordSecret:
          name: radarr-db-secret

      - name: lidarr-user
        ensure: present
        login: true
        passwordSecret:
          name: lidarr-db-secret

      - name: prowlarr-user
        ensure: present
        login: true
        passwordSecret:
          name: prowlarr-db-secret

      - name: pocketid-user
        ensure: present
        login: true
        passwordSecret:
          name: pocketid-db-secret
