apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superlogin
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: postgres-superlogin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-cluster
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-cluster
        property: username

