apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-pvc
  namespace: uptimekuma
  labels:
    app.kubernetes.io/name: uptimekuma
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
