---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-crs
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/cert-manager/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system 
  dependsOn:
    - name: infrastructure-cert-manager  