---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_key
      remoteRef:
        key: cert-manager
        property: cloudflare_api_key

