apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mp3-tagger-pvc
  namespace: mp3-tagger
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: mp3-tagger-pv
