---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-db-secret
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore

  data:
    - secretKey: username
      remoteRef:
        key: database/linkwarden
        property: db_user

    - secretKey: password
      remoteRef:
        key: database/linkwarden
        property: db_password

  target:
    name: linkwarden-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgresql://{{ .username }}:{{ .password }}@linkwarden-postgres-cluster-rw.linkwarden-db.svc.cluster.local:5432/linkwarden-db
        username: "{{ .username }}"
        password: "{{ .password }}"
