---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-db-secret
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore

  data:
    - secretKey: DB_USER
      remoteRef:
        key: database/linkwarden
        property: db_user

    - secretKey: DB_PASSWORD
      remoteRef:
        key: database/linkwarden
        property: db_password

  target:
    name: linkwarden-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgresql://{{ .DB_USER }}:{{ .DB_PASSWORD }}@linkwarden-postgres-cluster-rw.linkwarden-db.svc.cluster.local:5432/linkwarden-db
        DB_USER: "{{ .DB_USER }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
