apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: linkwarden-db
  namespace: database
  annotations:
    "cnpg.io/cluster": "postgres-cluster"
spec:
  name: linkwarden_db
  owner: linkwarden_user
  cluster:
    name: postgres-cluster
