---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
  labels:
    app: linkwarden
  annotations:
    ignore-check.kube-linter.io/run-as-non-root: "linkwarden/linkwarden requires root"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000

      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:v2.14.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: linkwarden-db-secret
            - secretRef:
                name: linkwarden-env-secret
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "4Gi"
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: "RuntimeDefault"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: linkwarden-data
              mountPath: /data
              subPath: data
            - name: linkwarden-tmp
              mountPath: /tmp
            - name: linkwarden-root-cache
              mountPath: /root/.cache
            - name: linkwarden-cache
              mountPath: /usr/local/share/.cache

      volumes:
        - name: linkwarden-data
          persistentVolumeClaim:
            claimName: linkwarden-pvc
        - name: linkwarden-tmp
          emptyDir: {}
        - name: linkwarden-root-cache
          emptyDir: {}
        - name: linkwarden-cache
          emptyDir: {}
