apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-env-secret
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: linkwarden-env-secret
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: linkwarden
        property: NEXTAUTH_SECRET
    - secretKey: NEXTAUTH_URL
      remoteRef:
        key: linkwarden
        property: NEXTAUTH_URL
