apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-secret
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: linkwarden-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: linkwarden
        property: POSTGRES_PASSWORD
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: linkwarden
        property: NEXTAUTH_SECRET
    - secretKey: NEXTAUTH_URL
      remoteRef:
        key: linkwarden
        property: NEXTAUTH_URL
    - secretKey: DATABASE_URL
      remoteRef:
        key: linkwarden
        property: DATABASE_URL
    - secretKey: POSTGRES_USER
      remoteRef:
        key: linkwarden
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: linkwarden
        property: POSTGRES_DB
