apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-pvc
  namespace: linkwarden
  labels:
    app.kubernetes.io/name: linkwarden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
