apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-pvc
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: linkwarden-pv
