---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-password-source
  namespace: database
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: openwebui-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: openwebui
        property: db_user

    - secretKey: password
      remoteRef:
        key: openwebui
        property: db_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db-secret
  namespace: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore

  data:
    - secretKey: username
      remoteRef:
        key: openwebui
        property: db_user
    - secretKey: password
      remoteRef:
        key: openwebui
        property: db_password

  target:
    name: openwebui-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgresql://{{ .username }}:{{ .password }}@postgres-cluster-rw.database.svc.cluster.local:5432/openwebui_db
        DB_USER: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
