apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openwebui-db-resource
  namespace: database
  annotations:
    "cnpg.io/cluster": "postgres-cluster"
spec:
  name: openwebui_db
  owner: openwebui_user
  cluster:
    name: postgres-cluster
