---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-password-source
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: openwebui-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: openwebui
        property: db_user

    - secretKey: password
      remoteRef:
        key: openwebui
        property: db_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db-secret
  namespace: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore

  target:
    name: openwebui-db-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: openwebui
        property: db_user

    - secretKey: password
      remoteRef:
        key: openwebui
        property: db_password
