apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-app-secret
  namespace: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: openwebui-app-secret
    creationPolicy: Owner
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: apps/openwebui
        property: webui_secret_key

    - secretKey: HF_TOKEN
      remoteRef:
        key: apps/openwebui
        property: hf_token

