apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-lan
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - certificate.yaml
configMapGenerator:
  - name: traefik-lan-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
