apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - comfyui
  - homepage
  #  - lidarr
  - linkwarden
  - openwebui
  #  - prowlarr
  #  - radarr
  #  - sonarr
  - wikijs
  - pocketid
  - gitea-runner
  - jellyfin
  - seerr
  #- autobrr
