apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autobrr
  - bentopdf
  - deemix
  - downtify  
  - gallery-dl
  - gitea-runner
  - houndarr
  - immich
  - lidarr
  - linkwarden
  - navidrome
  - ollama
  - openwebui
  - pocketid
  - prowlarr
  - radarr
  - seerr
  - slskd
  - sonarr
  - suggestarr
  - unpackerr
  - wikijs
  - yt-dlp
#  - comfyui
#  - homepage
#  - jellyfin
