apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superlogin
  namespace: lidarr-db
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: postgres-superlogin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: database/lidarr
        property: db_root_user
    - secretKey: password
      remoteRef:
        key: database/lidarr
        property: db_root_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-s3-secret
  namespace: lidarr-db
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: postgres-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: s3_key_id
      remoteRef:
        key: database/lidarr
        property: s3_key_id
    - secretKey: s3_secret_key
      remoteRef:
        key: database/lidarr
        property: s3_secret_key
