apiVersion: v1
kind: Namespace
metadata:
  name: lidarr-db
  labels:
    network-egress-apiserver: "true"
    network-egress-dns: "true"
    network-egress-s3: "true"
    network-ingress-cnpg: "true"
    network-ingress-monitoring: "true"
