apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
