apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: gpu-operator
      version: "v24.9.2"
      sourceRef:
        kind: HelmRepository
        name: nvidia-gpu-operator
        namespace: flux-system
  install:
    createNamespace: true
  values:
    driver:
      enabled: true
    toolkit:
      enabled: true
    devicePlugin:
      enabled: true
    dcgmExporter:
      enabled: true
