apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-slskd.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secret-gluetun.yaml
  - secret-slskd.yaml
  - secretstore.yaml
  - service.yaml
  - storage.yaml
