apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-configmap-secret
  namespace: slskd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kubernetes
    kind: SecretStore
  target:
    name: slskd-configmap-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: slskd-configmap
            items:
              - key: slskd.yml
  data:
    - secretKey: soulseek_username
      remoteRef:
        key: apps/slskd
        property: soulseek_username
    - secretKey: soulseek_password
      remoteRef:
        key: apps/slskd
        property: soulseek_password
    - secretKey: slskd_username
      remoteRef:
        key: apps/slskd
        property: slskd_username
    - secretKey: slskd_password
      remoteRef:
        key: apps/slskd
        property: slskd_password
    - secretKey: slskd_api_key
      remoteRef:
        key: apps/slskd
        property: slskd_api_key