apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-secret
  namespace: slskd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-global
    kind: ClusterSecretStore
  target:
    name: gluetun-secret
    creationPolicy: Owner
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: apps/slskd
        property: wireguard_provider

    - secretKey: VPN_TYPE
      remoteRef:
        key: apps/slskd
        property: wireguard_type

    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        key: apps/slskd
        property: wireguard_endpoint_ip

    - secretKey: WIREGUARD_ENDPOINT_PORT
      remoteRef:
        key: apps/slskd
        property: wireguard_endpoint_port

    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: apps/slskd
        property: wireguard_address

    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: apps/slskd
        property: wireguard_preshared_key

    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: apps/slskd
        property: wireguard_private_key

    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: apps/slskd
        property: wireguard_public_key

    - secretKey: FIREWALL_VPN_INPUT_PORTS
      remoteRef:
        key: apps/slskd
        property: wireguard_vpn_input_ports

    - secretKey: FIREWALL_INPUT_PORTS
      remoteRef:
        key: apps/slskd
        property: wireguard_input_ports

    - secretKey: DNS_UPSTREAM_RESOLVER_TYPE
      remoteRef:
        key: apps/slskd
        property: wireguard_upstream_resolver_type

    - secretKey: DNS_UPSTREAM_RESOLVERS
      remoteRef:
        key: apps/slskd
        property: wireguard_dns_resolvers

    - secretKey: FIREWALL_OUTBOUND_SUBNETS
      remoteRef:
        key: apps/slskd
        property: wireguard_outbound_subnets
