apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-downloads-pvc
  namespace: slskd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "share"
  volumeName: slskd-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-data-pvc
  namespace: slskd
  labels:
    app.kubernetes.io/name: slskd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
